sudo: required
services:
  - docker

language: c
compiler:
  #- clang
  - gcc

env:
    global:
      - OUT_REPO=tarantool/modules
    matrix:
      - OS=el DIST=6 PACK=rpm
      - OS=el DIST=7 PACK=rpm
      - OS=fedora DIST=20 PACK=rpm
      - OS=fedora DIST=21 PACK=rpm
      - OS=fedora DIST=22 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=ubuntu DIST=trusty PACK=deb PROD=msgpuck P_URI=https://github.com/tarantool/msgpuck.git
      - OS=ubuntu DIST=precise PACK=deb PROD=msgpuck P_URI=https://github.com/tarantool/msgpuck.git
      - OS=ubuntu DIST=vivid PACK=deb PROD=msgpuck P_URI=https://github.com/tarantool/msgpuck.git
      - OS=debian DIST=jessie PACK=deb PROD=msgpuck P_URI=https://github.com/tarantool/msgpuck.git
      - OS=debian DIST=wheezy PACK=deb PROD=msgpuck P_URI=https://github.com/tarantool/msgpuck.git
      - OS=debian DIST=stretch PACK=deb PROD=msgpuck P_URI=https://github.com/tarantool/msgpuck.git
      - PACK=none

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - gem install package_cloud

script:
  - bash travis.sh

notifications:
  irc: false
  email: true
